---
- name: initializing constellation
  debug:
    msg: initializing constellation 

- name: get public ip
  shell: dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com
  register: node_ip
  
- name: Copy constellation nodes file
  copy:
    src: "{{ role_path }}/files/constellation-nodes.json"
    dest: ~/alastria/tmp/constellation-nodes.json
    mode: 0755

- name: update constellation node files
  replace:
    path: ~/alastria/tmp/constellation-nodes.json
    regexp: '9000/"$'
    replace: '9000/",'
    
- name: update constellation nodes file
  lineinfile:
    path: ~/alastria/tmp/constellation-nodes.json
    regexp: '$]$'
    insertbefore: '^]$'
    line: '    "http://{{node_ip.stdout}}:9000/"'

- name: Fetch constellation_nodes updated
  fetch:
    src: ~/alastria/tmp/constellation-nodes.json
    dest: "{{ role_path }}/files/"
    flat: yes    

- name: generate configuration constellation file 
  template:
    src: "constellation.j2"
    dest: "~/alastria/data/constellation/constellation.conf"
    force: yes

- name: generate pair keys
  shell: cat ~/alastria/tmp/.account_pass | constellation-node --generatekeys=node
  args:
    chdir: ~/alastria/data/constellation/keystore

- name: Generate shell script to execute constellation service
  template:
    src: "startconstellation.j2"
    dest: "~/alastria/start-constellation.sh"
    mode: 0775
    force: yes 

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/constellation.service"
    dest: /lib/systemd/system/constellation.service
    mode: 0775

- name: Enable service constellation
  service:
    name: constellation
    enabled: yes