---
- name: init quorum
  debug:
    msg: "Init Quorum"

- name: get public ip
  shell: dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com
  register: node_ip

- name: create alastria directories
  file:
    path: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: '~/alastria/data/keystore', mode: '0440'}
    - { dest: '~/alastria/data/geth', mode: '0440'}
    - { dest: '~/alastria/data/constellation', mode: '0440'}
    - { dest: '~/alastria/data/constellation/data', mode: '0440'}
    - { dest: '~/alastria/data/constellation/keystore', mode: '0440'}
    - { dest: '~/alastria/logs', mode: '0440'}
    - { dest: '~/alastria/tmp', mode: '0440'}

- name: copy password to file
  copy:
    dest: ~/alastria/tmp/.account_pass
    content: |
      {{password}}

- name: initializing geth from genesis.json
  debug:
    msg: initializing Geth

- name: Copy genesis quorum file
  copy:
    src: "{{ role_path }}/files/genesis.json"
    dest: ~/alastria/data/genesis.json
    mode: 0755

- name: initializing Geth
  shell: geth --datadir ~/alastria/data init ~/alastria/data/genesis.json

- name: get bootnode
  shell: bootnode -genkey ~/alastria/data/geth/nodekey

- name: save enode in variable
  shell: bootnode -nodekey ~/alastria/data/geth/nodekey -writeaddress
  register: enode_key

- name: print enode key
  debug:
    msg: "enode://{{enode_key.stdout}}@{{node_ip.stdout}}:21000?discport=0"

#Update Permissioned Nodes Validator file 
- name: Copy permissioned nodes file
  copy:
    src: "{{playbook_dir}}/roles/alastria-validator-node/files/permissioned-nodes_validator.json"
    dest: ~/alastria/tmp/permissioned-nodes_validator.json
    mode: 0755

- name: update permissioned nodes validator file
  replace:
    dest: ~/alastria/tmp/permissioned-nodes_validator.json
    regexp: 'discport=0"$'
    replace: 'discport=0",'

- name: add new permissioned node regular
  lineinfile:
    path: ~/alastria/tmp/permissioned-nodes_validator.json
    regexp: '$]$'
    insertbefore: '^]$'
    line: '    "enode://{{enode_key.stdout}}@{{node_ip.stdout}}:21000?discport=0"'  

- name: Fetch permissioned nodes validator file to Validator Node
  fetch:
    src: ~/alastria/tmp/permissioned-nodes_validator.json
    dest: "{{playbook_dir}}/roles/alastria-validator-node/files/"
    flat: yes 

- name: copy permissioned-nodes to data
  copy:
    src: "{{role_path}}/files/permissioned-nodes_general.json"
    dest: ~/alastria/data/permissioned-nodes.json
    mode: 0755

- name: copy permissioned-nodes to static nodes
  copy:
    src: "{{role_path}}/files/permissioned-nodes_general.json"
    dest: ~/alastria/data/static-nodes.json
    mode: 0755

- name: create new account
  shell: geth --datadir ~/alastria/data --password ~/alastria/tmp/.account_pass account new

- name: Generate shell script to execute geth service
  template:
    src: "startquorum.j2"
    dest: "~/alastria/start-quorum.sh"
    mode: 0775
    force: yes

- name: Copy health check 
  copy:
    src: "{{ role_path }}/files/health-check.sh"
    dest: ~/alastria/health-check.sh
    mode: 0775

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/geth.service"
    dest: /lib/systemd/system/geth.service
    mode: 0775

- name: Enable service geth
  service:
    name: geth
    enabled: yes