---
- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "ubuntu-dependencies.yml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "rhel-dependencies.yml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: install golang
  import_tasks: "install-go.yaml"

- name: install quorum
  import_tasks: "install-quorum.yaml"

- name: init quorum
  import_tasks: "init-quorum.yaml"

- name: start node
  import_tasks: "start-node.yaml"
  when: first_node

- name: clean files
  import_tasks: "clean-files.yaml"